name: Cypress Test UI Automation After Office Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL_AMAZON: 'https://www.amazon.com'  # URL yang dipakai di cy.visit()
      BASE_URL_YOUTUBE: 'https://www.youtube.com'  # URL yang dipakai di cy.visit()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with mochawesome reporter
        run: npm run run_test

      - name: Debug folder structure
        run: ls -R cypress

      - name: Debug report output
        run: ls -R cypress/reports

      - name: Upload Cypress Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html

      - name: Upload videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy stages
        run: echo "Deploy App"
  non-functional-test:
    runs-on: ubuntu-latest
    steps:
      - name: non func test
        run: echo "non func test"