name: Cypress Test UI Automation After Office Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build stages
        run: echo "build App"

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      BASE_URL_AMAZON: 'https://www.amazon.com'  # URL yang dipakai di cy.visit()
      BASE_URL_YOUTUBE: 'https://www.youtube.com'  # URL yang dipakai di cy.visit()
      BASE_URL_AGODA: 'https://www.agoda.com/id-id/'  # URL yang dipakai di cy.visit()

      # Gunakan GitHub secrets untuk environment variables
      CONTACT_FIRST_NAME: ${{ secrets.CONTACT_FIRST_NAME }}
      CONTACT_LAST_NAME: ${{ secrets.CONTACT_LAST_NAME }}
      CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      CONTACT_PHONE_NUMBER: ${{ secrets.CONTACT_PHONE_NUMBER }}
      PASSENGER_FIRST_NAME: ${{ secrets.PASSENGER_FIRST_NAME }}
      PASSENGER_LAST_NAME: ${{ secrets.PASSENGER_LAST_NAME }}
      PASSENGER_DATE: ${{ secrets.PASSENGER_DATE }}
      PASSENGER_YEAR: ${{ secrets.PASSENGER_YEAR }}
      PASSENGER_PASSPORT: ${{ secrets.PASSENGER_PASSPORT }}
      PASSPORT_DATE: ${{ secrets.PASSPORT_DATE }}
      PASSPORT_YEAR: ${{ secrets.PASSPORT_YEAR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with mochawesome reporter
        run: npm run run_test

      - name: Debug folder structure
        run: ls -R cypress

      - name: Debug report output
        run: ls -R cypress/reports

      - name: Upload Cypress Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html

      - name: Upload videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy stages
        run: echo "Deploy App"

  non-functional-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: non func test
        run: echo "non func test"
